
var MainObj = [
    {
        id: 1,
        dishname: "Butter Chicken",
        restaurantName: "Punjabi Dhaba",
        avgrating: 4.8,
        veg: false,
        prize: 300,
        imgURL: "https://source.unsplash.com/1600x800/?chicken-dish",
        foodDisc: "Chicken cooked in a rich buttery tomato sauce",
        deliveryCharges: 75
    },
    {
        id: 2,
        dishname: "Veg Biryani",
        restaurantName: "South Indian Spices",
        avgrating: 4.2,
        veg: true,
        prize: 200,
        imgURL: "https://source.unsplash.com/1600x800/?veg-biryani",
        foodDisc: "Fragrant rice cooked with vegetables and spices",
        deliveryCharges: 60
    },
    {
        id: 3,
        dishname: "Dal Makhani",
        restaurantName: "Punjabi Tadka",
        avgrating: 4.4,
        veg: true,
        prize: 180,
        imgURL: "https://source.unsplash.com/1600x800/?dal-curry",
        foodDisc: "Black lentils simmered with tomatoes and spices",
        deliveryCharges: 55
    },
    {
        id: 4,
        dishname: "Samosa",
        restaurantName: "Kolkata Chaat House",
        avgrating: 4.5,
        veg: true,
        prize: 20,
        imgURL: "https://source.unsplash.com/1600x800/?samosa",
        foodDisc: "Crispy fried pastry filled with spiced potatoes and peas",
        deliveryCharges: 35
    },
    {
        id: 5,
        dishname: "Paneer Tikka Masala",
        restaurantName: "Tandoori Kitchen",
        avgrating: 4.5,
        veg: true,
        prize: 250,
        imgURL: "https://source.unsplash.com/1600x800/?paneer-tikka-masala",
        foodDisc: "Paneer tikka cooked in a creamy tomato sauce",
        deliveryCharges: 50
    },
    {
        id: 6,
        dishname: "Chole Bhature",
        restaurantName: "Punjabi Junction",
        avgrating: 4.3,
        veg: true,
        prize: 150,
        imgURL: "https://source.unsplash.com/1600x800/?chole-bhature",
        foodDisc: "Spicy chickpea curry served with fried bread",
        deliveryCharges: 40
    },
    {
        id: 7,
        dishname: "Tandoori Chicken",
        restaurantName: "Tandoori Junction",
        avgrating: 4.6,
        veg: false,
        prize: 280,
        imgURL: "https://source.unsplash.com/1600x800/?tandoori-chicken",
        foodDisc: "Juicy chicken marinated in yogurt and spices, cooked in a tandoor",
        deliveryCharges: 70
    },
    {
        id: 8,
        dishname: "Aloo Gobi",
        restaurantName: "Delhi Spice",
        avgrating: 4.1,
        veg: true,
        prize: 170,
        imgURL: "https://source.unsplash.com/1600x800/?indian-curry",
        foodDisc: "Potatoes and cauliflower cooked with spices",
        deliveryCharges: 50
    }, {
        id: 9,
        dishname: "Chicken Tikka",
        restaurantName: "Mughlai Flavours",
        avgrating: 4.7,
        veg: false,
        prize: 320,
        imgURL: "https://source.unsplash.com/1600x800/?chicken-tikka",
        foodDisc: "Juicy pieces of chicken marinated in spices and cooked in a tandoor",
        deliveryCharges: 80
    },
    {
        id: 10,
        dishname: "Mutton Rogan Josh",
        restaurantName: "Kashmiri Kitchen",
        avgrating: 4.3,
        veg: false,
        prize: 400,
        imgURL: "https://source.unsplash.com/1600x800/?spicy-meat",
        foodDisc: "Tender pieces of mutton cooked in a spicy gravy",
        deliveryCharges: 90
    },
    {
        id: 11,
        dishname: "Hamburger",
        restaurantName: "Burger Joint",
        avgrating: 4.5,
        veg: false,
        prize: 150,
        imgURL: "https://source.unsplash.com/1600x800/?hamburger",
        foodDisc: "Beef patty served on a bun with lettuce, tomato, and cheese",
        deliveryCharges: 30
    },
    {
        id: 12,
        dishname: "Hot Dog",
        restaurantName: "Hot Dog Stand",
        avgrating: 4.2,
        veg: false,
        prize: 80,
        imgURL: "https://source.unsplash.com/1600x800/?hotdog",
        foodDisc: "Grilled sausage served in a long bun with mustard and ketchup",
        deliveryCharges: 20
    },
    {
        id: 13,
        dishname: "Mac and Cheese",
        restaurantName: "Mac Shack",
        avgrating: 4.4,
        veg: true,
        prize: 120,
        imgURL: "https://source.unsplash.com/1600x800/?mac-and-cheese",
        foodDisc: "Pasta cooked with a creamy cheese sauce",
        deliveryCharges: 25
    },
    {
        id: 14,
        dishname: "BBQ Ribs",
        restaurantName: "Rib House",
        avgrating: 4.8,
        veg: false,
        prize: 300,
        imgURL: "https://source.unsplash.com/1600x800/?bbq-ribs",
        foodDisc: "Slow-cooked pork ribs glazed with BBQ sauce",
        deliveryCharges: 50
    },
    {
        id: 15,
        dishname: "Fried Chicken",
        restaurantName: "Southern Kitchen",
        avgrating: 4.6,
        veg: false,
        prize: 250,
        imgURL: "https://source.unsplash.com/1600x800/?fried-chicken",
        foodDisc: "Crispy fried chicken served with mashed potatoes and gravy",
        deliveryCharges: 40
    },
    {
        id: 16,
        dishname: "Steak",
        restaurantName: "Steakhouse",
        avgrating: 4.9,
        veg: false,
        prize: 500,
        imgURL: "https://source.unsplash.com/1600x800/?steak",
        foodDisc: "Juicy steak served with vegetables and mashed potatoes",
        deliveryCharges: 100
    }, {
        id: 21,
        dishname: "Kung Pao Chicken",
        restaurantName: "Spice Garden",
        avgrating: 4.5,
        veg: false,
        prize: 250,
        imgURL: "https://source.unsplash.com/1600x800/?kung-pao-chicken",
        foodDisc: "Spicy chicken stir-fry with peanuts and vegetables",
        deliveryCharges: 50
    },
    {
        id: 22,
        dishname: "Hot and Sour Soup",
        restaurantName: "Golden Wok",
        avgrating: 4.2,
        veg: true,
        prize: 100,
        imgURL: "https://source.unsplash.com/1600x800/?hot-and-sour-soup",
        foodDisc: "Spicy soup with vegetables, tofu, and mushrooms",
        deliveryCharges: 20
    },
    {
        id: 23,
        dishname: "Chow Mein",
        restaurantName: "Wok n Roll",
        avgrating: 4.4,
        veg: true,
        prize: 150,
        imgURL: "https://source.unsplash.com/1600x800/?chow-mein",
        foodDisc: "Stir-fried noodles with vegetables and meat or tofu",
        deliveryCharges: 30
    },
    {
        id: 24,
        dishname: "Dumplings",
        restaurantName: "Dumpling House",
        avgrating: 4.8,
        veg: false,
        prize: 180,
        imgURL: "https://source.unsplash.com/1600x800/?dumplings",
        foodDisc: "Steamed or fried dumplings filled with meat or vegetables",
        deliveryCharges: 35
    },
    {
        id: 25,
        dishname: "Szechuan Shrimp",
        restaurantName: "Dragon Palace",
        avgrating: 4.6,
        veg: false,
        prize: 280,
        imgURL: "https://source.unsplash.com/1600x800/?szechuan-shrimp",
        foodDisc: "Spicy shrimp stir-fry with vegetables",
        deliveryCharges: 55
    },
    {
        id: 26,
        dishname: "Peking Duck",
        restaurantName: "Dynasty Palace",
        avgrating: 4.9,
        veg: false,
        prize: 800,
        imgURL: "https://source.unsplash.com/1600x800/?peking-duck",
        foodDisc: "Roasted duck served with pancakes, scallions, and hoisin sauce",
        deliveryCharges: 120
    }, {
        id: 31,
        dishname: "Gulab Jamun",
        restaurantName: "Sweets Corner",
        avgrating: 4.7,
        veg: true,
        prize: 120,
        imgURL: "https://source.unsplash.com/1600x800/?gulab-jamun",
        foodDisc: "Deep-fried dumplings made of milk solids, soaked in syrup",
        deliveryCharges: 25
        , sweets: true,

    },
    {
        id: 32,
        dishname: "Rasmalai",
        restaurantName: "Bengali Sweets",
        avgrating: 4.5,
        veg: true,
        prize: 150,
        imgURL: "https://media.istockphoto.com/id/1411786526/photo/rasmalai.jpg?b=1&s=612x612&w=0&k=20&c=o91tSJsn7o_Kp9QDUbq6IA1LieNPD_g_5ASQjFamwKE=",
        foodDisc: "Soft cheese dumplings soaked in sweetened milk",
        deliveryCharges: 30
        , sweets: true,

    },
    {
        id: 33,
        dishname: "Ladoo",
        restaurantName: "Sri Krishna Sweets",
        avgrating: 4.8,
        veg: true,
        prize: 100,
        imgURL: "https://source.unsplash.com/1600x800/?ladoo",
        foodDisc: "Round balls made of flour, sugar, and ghee",
        deliveryCharges: 20
        , sweets: true,

    },
    {
        id: 34,
        dishname: "Jalebi",
        restaurantName: "Haldiram's",
        avgrating: 4.4,
        veg: true,
        prize: 80,
        imgURL: "https://source.unsplash.com/1600x800/?jalebi",
        foodDisc: "Crisp and juicy deep-fried batter soaked in syrup",
        deliveryCharges: 15
        , sweets: true,

    },
    {
        id: 35,
        dishname: "Barfi",
        restaurantName: "Moti Mahal Delux",
        avgrating: 4.6,
        veg: true,
        prize: 200,
        imgURL: "https://images.pexels.com/photos/4016512/pexels-photo-4016512.jpeg?auto=compress&cs=tinysrgb&w=600",
        foodDisc: "Sweet and dense milk-based fudge",
        deliveryCharges: 35
        , sweets: true,

    },
    {
        id: 36,
        dishname: "Kaju Katli",
        restaurantName: "Bikanervala",
        avgrating: 4.7,
        veg: true,
        prize: 250,
        imgURL: "https://source.unsplash.com/1600x800/?kaju-katli",
        foodDisc: "Thin diamond-shaped sweets made of cashew nuts and sugar",
        deliveryCharges: 40
        , sweets: true,

    },
    {
        id: 37,
        dishname: "Gajar ka Halwa",
        restaurantName: "Punjabi Rasoi",
        avgrating: 4.5,
        veg: true,
        prize: 180,
        imgURL: "https://images.unsplash.com/photo-1610432589024-5f02f76549cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FqYXIlMjBoYWx3YXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
        foodDisc: "Sweet and rich dessert made of grated carrots, milk, and sugar",
        deliveryCharges: 30
        , sweets: true,

    },
    {
        id: 38,
        dishname: "Kulfi",
        restaurantName: "Kuremal Mohan Lal Kulfi Wale",
        avgrating: 4.9,
        veg: true,
        prize: 100,
        imgURL: "https://images.pexels.com/photos/4705113/pexels-photo-4705113.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        foodDisc: "Frozen dairy dessert, similar to ice cream but denser and creamier",
        deliveryCharges: 20
        , sweets: true,

    },

]

var RestaurantsData = [
    {
        id: 1,
        name: "Taste of India",
        description: "Authentic Indian cuisine with a modern twist",
        imgURL: "https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        distance: 1.2,
        rating: 3.0,
        avgPrize:300,
        dishes: [
            {
                dishName: "Butter Chicken",
                dishDescription: "Tender chicken in a rich and creamy tomato-based sauce",
                dishPrice: 12.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "30-45 mins",
                avgRating: 4.7,
                imgURL: "https://source.unsplash.com/1600x800/?butterchicken",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Samosas",
                dishDescription: "Crispy pastry filled with spiced potatoes and peas",
                dishPrice: 6.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-45 mins",
                avgRating: 4.3,
                imgURL: "https://source.unsplash.com/1600x800/?samosas",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Chana Masala",
                dishDescription: "Spiced chickpeas in a tomato-based sauce",
                dishPrice: 10.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-45 mins",
                avgRating: 4.2,
                imgURL: "https://source.unsplash.com/1600x800/?chanamasala",
                deliveryCharges: 2.99,
            },
        ],
    },
    {
        id: 2,
        name: "Spice House",
        description: "Family-owned restaurant serving traditional Indian dishes",
        imgURL: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        distance: 1.4,
        rating: 4.8,
        avgPrize:400,
        dishes: [
            {
                dishName: "Biryani",
                dishDescription: "Fragrant rice with tender pieces of chicken or lamb",
                dishPrice: 11.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "25-35 mins",
                avgRating: 4.5,
                imgURL: "https://source.unsplash.com/1600x800/?biryani",
                deliveryCharges: 1.99,
            },
            {
                dishName: "Palak Paneer",
                dishDescription: "Creamy spinach with cubes of paneer cheese",
                dishPrice: 9.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "25-35 mins",
                avgRating: 4.1,
                imgURL: "https://source.unsplash.com/1600x800/?palakpaneer",
                deliveryCharges: 1.99,
            },
            {
                dishName: "Tandoori Chicken",
                dishDescription: "Marinated chicken cooked in a traditional clay oven",
                dishPrice: 13.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "25-35 mins",
                avgRating: 4.6,
                imgURL: "https://source.unsplash.com/1600x800/?tandoorichicken",
                deliveryCharges: 1.99,
            },
        ],
    },
    {
        id: 3,
        name: "Burger Bazaar",
        description: "Gourmet burgers made with fresh, locally sourced ingredients",
        distance: 0.5,
        imgURL: "https://images.pexels.com/photos/3616956/pexels-photo-3616956.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        rating: 3.5,
        avgPrize:250,
        dishes: [
            {
                dishName: "Classic Cheeseburger",
                dishDescription: "Beef patty with melted cheddar cheese, lettuce, tomato, and onion",
                dishPrice: 9.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "20-30 mins",
                avgRating: 4.9,
                imgURL: "https://source.unsplash.com/1600x800/?burger",
                deliveryCharges: 2.99,
            },
            {
                dishName: "BBQ Pulled Pork Sandwich",
                dishDescription: "Slow-cooked pulled pork with tangy BBQ sauce on a brioche bun",
                dishPrice: 11.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "20-30 mins",
                avgRating: 4.7,
                imgURL: "https://source.unsplash.com/1600x800/?pulledpork",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Truffle Fries",
                dishDescription: "Crispy fries tossed in truffle oil and topped with parmesan cheese",
                dishPrice: 6.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "20-30 mins",
                avgRating: 4.5,
                imgURL: "https://source.unsplash.com/1600x800/?fries",
                deliveryCharges: 2.99,
            },
        ],
    },
    {
        id: 4,
        name: "Pizza Palace",
        description: "Wood-fired pizzas made with homemade dough and fresh toppings",
        imgURL: "https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        distance: 3,
        rating: 3.9,
        avgPrize:500,
        dishes: [
            {
                dishName: "Margherita Pizza",
                dishDescription: "Tomato sauce, mozzarella cheese, and fresh basil",
                dishPrice: 12.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-40 mins",
                avgRating: 4.8,
                imgURL: "https://source.unsplash.com/1600x800/?pizza",
                deliveryCharges: 1.99,
            },
            {
                dishName: "Meat Lovers Pizza",
                dishDescription: "Tomato sauce, mozzarella cheese, pepperoni, sausage, and bacon",
                dishPrice: 15.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "30-40 mins",
                avgRating: 4.6,
                imgURL: "https://source.unsplash.com/1600x800/?meatpizza",
                deliveryCharges: 1.99,
            },
            {
                dishName: "Garlic Knots",
                dishDescription: "Warm bread knots brushed with garlic butter and parmesan cheese",
                dishPrice: 5.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-40 mins",
                avgRating: 4.3,
                imgURL: "https://source.unsplash.com/1600x800/?garlic-bread",
                deliveryCharges: 2.39,
            },
        ],
    },
    {
        id: 5,
        name: "Tandoori Times",
        description: "Authentic Indian dishes made with traditional Tandoori cooking methods",
        distance: "2 miles",
        imgURL: "https://images.pexels.com/photos/9738994/pexels-photo-9738994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        rating: 4.7,
        avgPrize:400,
        dishes: [
            {
                dishName: "Butter Chicken",
                dishDescription: "Tandoori chicken in a creamy tomato sauce with aromatic spices",
                dishPrice: 12.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "40-50 mins",
                avgRating: 4.9,
                imgURL: "https://source.unsplash.com/1600x800/?butter-chicken",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Chicken Tikka Masala",
                dishDescription: "Tandoori chicken in a creamy tomato sauce with Indian spices",
                dishPrice: 13.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "40-50 mins",
                avgRating: 4.7,
                imgURL: "https://source.unsplash.com/1600x800/?chicken-tikka-masala",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Samosas",
                dishDescription: "Crispy pastry filled with spiced potatoes and peas",
                dishPrice: 6.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-40 mins",
                avgRating: 4.4,
                imgURL: "https://source.unsplash.com/1600x800/?samosa",
                deliveryCharges: 1.99,
            },
        ],
    },
    {
        id: 6,
        name: "Curry House",
        description: "Indian and Pakistani cuisine with a modern twist",
        distance: 4,
        imgURL: "https://images.pexels.com/photos/9809033/pexels-photo-9809033.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        rating: 4.0,
        avgPrize:600,
        dishes: [
            {
                dishName: "Biryani",
                dishDescription: "Fragrant rice dish cooked with meat, spices, and herbs",
                dishPrice: 15.99,
                isSweet: false,
                isVeg: false,
                deliveryTime: "40-50 mins",
                avgRating: 4.8,
                imgURL: "https://source.unsplash.com/1600x800/?biryani",
                deliveryCharges: 3.99,
            },
            {
                dishName: "Saag Paneer",
                dishDescription: "Spinach and cottage cheese curry with spices",
                dishPrice: 12.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "40-50 mins",
                avgRating: 4.6,
                imgURL: "https://source.unsplash.com/1600x800/?saag-paneer",
                deliveryCharges: 2.99,
            },
            {
                dishName: "Chana Masala",
                dishDescription: "Spicy chickpea curry with onions and tomatoes",
                dishPrice: 11.99,
                isSweet: false,
                isVeg: true,
                deliveryTime: "30-40 mins",
                avgRating: 4.3,
                imgURL: "https://source.unsplash.com/1600x800/?chana-masala",
                deliveryCharges: 2.49,
            },
        ],
    },
]
export { MainObj }
export { RestaurantsData }
